services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 10s

  topic-init:
    image: apache/kafka:3.7.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/scripts/create-topics.sh"]
    volumes:
      - ./scripts/create-topics.sh:/scripts/create-topics.sh:ro


  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  producer:
    build:
      context: ./producer
    depends_on:
      topic-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      RAW_TOPIC: raw_sales_orders
      PRODUCER_INTERVAL_MS: 1500
    restart: on-failure

  processor:
    build:
      context: ./processor
    depends_on:
      topic-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_RAW_SALES_ORDERS_TOPIC: raw_sales_orders
      APP_SALES_ORDER_TOPIC: sales_order
      APP_SALES_ORDER_LINE_ITEM_TOPIC: sales_order_line_item
      APP_CUSTOMER_SALES_TOPIC: customer_sales
      APP_CONSUMER_GROUP_ID: realtime-flink-processor-local
      APP_CHECKPOINT_INTERVAL_MS: 10000
    restart: on-failure
