kafkaBootstrapServers: kafka-qa.kafka.svc.cluster.local:9092
producer:
  replicas: 1
  image:
    repository: my-registry/realtime-sales-producer
    tag: 0.1.0
    pullPolicy: IfNotPresent
  intervalMs: 2000
processor:
  replicas: 1
  image:
    repository: my-registry/realtime-sales-processor
    tag: 0.1.0
    pullPolicy: IfNotPresent
  consumerGroupId: realtime-flink-processor-qa
kafka:
  enabled: false