spring:
  application:
    name: realtime-processor
app:
  kafka-bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
  raw-sales-orders-topic: ${APP_RAW_SALES_ORDERS_TOPIC:raw_sales_orders}
  sales-order-topic: ${APP_SALES_ORDER_TOPIC:sales_order}
  sales-order-line-item-topic: ${APP_SALES_ORDER_LINE_ITEM_TOPIC:sales_order_line_item}
  customer-sales-topic: ${APP_CUSTOMER_SALES_TOPIC:customer_sales}
  consumer-group-id: ${APP_CONSUMER_GROUP_ID:realtime-flink-processor}
  checkpoint-interval-ms: ${APP_CHECKPOINT_INTERVAL_MS:10000}