apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realtime-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paulchen8206/Full-Stack-Modern-Data-Architecture-and-Engineering.git
    targetRevision: main
    path: charts/realtime-app
    helm:
      releaseName: realtime-dev
      valueFiles:
      - ../../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: realtime-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true