kafkaBootstrapServers: realtime-dev-kafka:9092
producer:
  replicas: 1
  image:
    repository: realtime-sales-producer
    tag: 0.1.0
    pullPolicy: Never
  intervalMs: 1000
processor:
  replicas: 1
  image:
    repository: realtime-sales-processor
    tag: 0.1.0
    pullPolicy: Never
  consumerGroupId: realtime-flink-processor-dev
kafkaUi:
  enabled: true
minio:
  enabled: true
postgres:
  enabled: true
connect:
  enabled: true
  image:
    repository: realtime-sales-connect
    tag: 0.1.0
    pullPolicy: Never
dbt:
  enabled: true
  image:
    repository: realtime-sales-dbt
    tag: 0.1.0
    pullPolicy: Never
airflow:
  enabled: true
  image:
    repository: realtime-sales-airflow
    tag: 0.1.0
    pullPolicy: Never
mdm:
  enabled: true
  writer:
    image:
      repository: realtime-sales-mdm-writer
      tag: 0.1.0
      pullPolicy: Never
  cdcProducer:
    image:
      repository: realtime-sales-mdm-cdc-producer
      tag: 0.1.0
      pullPolicy: Never
  pysparkSync:
    image:
      repository: realtime-sales-mdm-pyspark-sync
      tag: 0.1.0
      pullPolicy: Never
observability:
  enabled: true
kafka:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
    tag: 4.0.0-debian-12-r10
  provisioning:
    enabled: true
    waitForKafka: false
  extraConfig: |-
    default.replication.factor=1
    min.insync.replicas=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    share.coordinator.state.topic.replication.factor=1
    share.coordinator.state.topic.min.isr=1